using Pkg
Pkg.add("Plots")
Pkg.add("DifferentialEquations")
Pkg.add("ParameterizedFunctions")
Pkg.add("DataFrames")
Pkg.add("IterableTables")
Pkg.add("ORCA")
Pkg.add("Optim")
Pkg.add("PrettyTables")
Pkg.add("DiffEqSensitivity")
Pkg.add("ODEInterfaceDiffEq")
Pkg.add("PyPlot")
Pkg.add("CSV")
